/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedMedicationsRouteImport } from './routes/_authenticated/medications'
import { Route as AuthenticatedInteractionsRouteImport } from './routes/_authenticated/interactions'
import { Route as AuthenticatedIngredientsRouteImport } from './routes/_authenticated/ingredients'
import { Route as AuthenticatedEncountersRouteImport } from './routes/_authenticated/encounters'
import { Route as AuthenticatedContraindicationsRouteImport } from './routes/_authenticated/contraindications'
import { Route as AuthenticatedPatientsPatientIdRouteImport } from './routes/_authenticated/patients.$patientId'
import { Route as AuthenticatedMedicationsNewRouteImport } from './routes/_authenticated/medications.new'
import { Route as AuthenticatedMedicationsLinkIngredientRouteImport } from './routes/_authenticated/medications.link-ingredient'
import { Route as AuthenticatedMedicationsMedicationIdRouteImport } from './routes/_authenticated/medications.$medicationId'
import { Route as AuthenticatedInteractionsNewRouteImport } from './routes/_authenticated/interactions.new'
import { Route as AuthenticatedIngredientsNewRouteImport } from './routes/_authenticated/ingredients.new'
import { Route as AuthenticatedEncountersEncounterIdRouteImport } from './routes/_authenticated/encounters.$encounterId'
import { Route as AuthenticatedContraindicationsNewRouteImport } from './routes/_authenticated/contraindications.new'
import { Route as AuthenticatedMedicationsMedicationIdEditRouteImport } from './routes/_authenticated/medications.$medicationId.edit'
import { Route as AuthenticatedInteractionsRuleIdEditRouteImport } from './routes/_authenticated/interactions.$ruleId.edit'
import { Route as AuthenticatedIngredientsIngredientIdEditRouteImport } from './routes/_authenticated/ingredients.$ingredientId.edit'
import { Route as AuthenticatedContraindicationsRuleIdEditRouteImport } from './routes/_authenticated/contraindications.$ruleId.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMedicationsRoute =
  AuthenticatedMedicationsRouteImport.update({
    id: '/medications',
    path: '/medications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInteractionsRoute =
  AuthenticatedInteractionsRouteImport.update({
    id: '/interactions',
    path: '/interactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIngredientsRoute =
  AuthenticatedIngredientsRouteImport.update({
    id: '/ingredients',
    path: '/ingredients',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEncountersRoute = AuthenticatedEncountersRouteImport.update({
  id: '/encounters',
  path: '/encounters',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContraindicationsRoute =
  AuthenticatedContraindicationsRouteImport.update({
    id: '/contraindications',
    path: '/contraindications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientsPatientIdRoute =
  AuthenticatedPatientsPatientIdRouteImport.update({
    id: '/$patientId',
    path: '/$patientId',
    getParentRoute: () => AuthenticatedPatientsRoute,
  } as any)
const AuthenticatedMedicationsNewRoute =
  AuthenticatedMedicationsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedMedicationsRoute,
  } as any)
const AuthenticatedMedicationsLinkIngredientRoute =
  AuthenticatedMedicationsLinkIngredientRouteImport.update({
    id: '/link-ingredient',
    path: '/link-ingredient',
    getParentRoute: () => AuthenticatedMedicationsRoute,
  } as any)
const AuthenticatedMedicationsMedicationIdRoute =
  AuthenticatedMedicationsMedicationIdRouteImport.update({
    id: '/$medicationId',
    path: '/$medicationId',
    getParentRoute: () => AuthenticatedMedicationsRoute,
  } as any)
const AuthenticatedInteractionsNewRoute =
  AuthenticatedInteractionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedInteractionsRoute,
  } as any)
const AuthenticatedIngredientsNewRoute =
  AuthenticatedIngredientsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedIngredientsRoute,
  } as any)
const AuthenticatedEncountersEncounterIdRoute =
  AuthenticatedEncountersEncounterIdRouteImport.update({
    id: '/$encounterId',
    path: '/$encounterId',
    getParentRoute: () => AuthenticatedEncountersRoute,
  } as any)
const AuthenticatedContraindicationsNewRoute =
  AuthenticatedContraindicationsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedContraindicationsRoute,
  } as any)
const AuthenticatedMedicationsMedicationIdEditRoute =
  AuthenticatedMedicationsMedicationIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedMedicationsMedicationIdRoute,
  } as any)
const AuthenticatedInteractionsRuleIdEditRoute =
  AuthenticatedInteractionsRuleIdEditRouteImport.update({
    id: '/$ruleId/edit',
    path: '/$ruleId/edit',
    getParentRoute: () => AuthenticatedInteractionsRoute,
  } as any)
const AuthenticatedIngredientsIngredientIdEditRoute =
  AuthenticatedIngredientsIngredientIdEditRouteImport.update({
    id: '/$ingredientId/edit',
    path: '/$ingredientId/edit',
    getParentRoute: () => AuthenticatedIngredientsRoute,
  } as any)
const AuthenticatedContraindicationsRuleIdEditRoute =
  AuthenticatedContraindicationsRuleIdEditRouteImport.update({
    id: '/$ruleId/edit',
    path: '/$ruleId/edit',
    getParentRoute: () => AuthenticatedContraindicationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/contraindications': typeof AuthenticatedContraindicationsRouteWithChildren
  '/encounters': typeof AuthenticatedEncountersRouteWithChildren
  '/ingredients': typeof AuthenticatedIngredientsRouteWithChildren
  '/interactions': typeof AuthenticatedInteractionsRouteWithChildren
  '/medications': typeof AuthenticatedMedicationsRouteWithChildren
  '/overview': typeof AuthenticatedOverviewRoute
  '/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/contraindications/new': typeof AuthenticatedContraindicationsNewRoute
  '/encounters/$encounterId': typeof AuthenticatedEncountersEncounterIdRoute
  '/ingredients/new': typeof AuthenticatedIngredientsNewRoute
  '/interactions/new': typeof AuthenticatedInteractionsNewRoute
  '/medications/$medicationId': typeof AuthenticatedMedicationsMedicationIdRouteWithChildren
  '/medications/link-ingredient': typeof AuthenticatedMedicationsLinkIngredientRoute
  '/medications/new': typeof AuthenticatedMedicationsNewRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/contraindications/$ruleId/edit': typeof AuthenticatedContraindicationsRuleIdEditRoute
  '/ingredients/$ingredientId/edit': typeof AuthenticatedIngredientsIngredientIdEditRoute
  '/interactions/$ruleId/edit': typeof AuthenticatedInteractionsRuleIdEditRoute
  '/medications/$medicationId/edit': typeof AuthenticatedMedicationsMedicationIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/contraindications': typeof AuthenticatedContraindicationsRouteWithChildren
  '/encounters': typeof AuthenticatedEncountersRouteWithChildren
  '/ingredients': typeof AuthenticatedIngredientsRouteWithChildren
  '/interactions': typeof AuthenticatedInteractionsRouteWithChildren
  '/medications': typeof AuthenticatedMedicationsRouteWithChildren
  '/overview': typeof AuthenticatedOverviewRoute
  '/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/contraindications/new': typeof AuthenticatedContraindicationsNewRoute
  '/encounters/$encounterId': typeof AuthenticatedEncountersEncounterIdRoute
  '/ingredients/new': typeof AuthenticatedIngredientsNewRoute
  '/interactions/new': typeof AuthenticatedInteractionsNewRoute
  '/medications/$medicationId': typeof AuthenticatedMedicationsMedicationIdRouteWithChildren
  '/medications/link-ingredient': typeof AuthenticatedMedicationsLinkIngredientRoute
  '/medications/new': typeof AuthenticatedMedicationsNewRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/contraindications/$ruleId/edit': typeof AuthenticatedContraindicationsRuleIdEditRoute
  '/ingredients/$ingredientId/edit': typeof AuthenticatedIngredientsIngredientIdEditRoute
  '/interactions/$ruleId/edit': typeof AuthenticatedInteractionsRuleIdEditRoute
  '/medications/$medicationId/edit': typeof AuthenticatedMedicationsMedicationIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/contraindications': typeof AuthenticatedContraindicationsRouteWithChildren
  '/_authenticated/encounters': typeof AuthenticatedEncountersRouteWithChildren
  '/_authenticated/ingredients': typeof AuthenticatedIngredientsRouteWithChildren
  '/_authenticated/interactions': typeof AuthenticatedInteractionsRouteWithChildren
  '/_authenticated/medications': typeof AuthenticatedMedicationsRouteWithChildren
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/_authenticated/contraindications/new': typeof AuthenticatedContraindicationsNewRoute
  '/_authenticated/encounters/$encounterId': typeof AuthenticatedEncountersEncounterIdRoute
  '/_authenticated/ingredients/new': typeof AuthenticatedIngredientsNewRoute
  '/_authenticated/interactions/new': typeof AuthenticatedInteractionsNewRoute
  '/_authenticated/medications/$medicationId': typeof AuthenticatedMedicationsMedicationIdRouteWithChildren
  '/_authenticated/medications/link-ingredient': typeof AuthenticatedMedicationsLinkIngredientRoute
  '/_authenticated/medications/new': typeof AuthenticatedMedicationsNewRoute
  '/_authenticated/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/_authenticated/contraindications/$ruleId/edit': typeof AuthenticatedContraindicationsRuleIdEditRoute
  '/_authenticated/ingredients/$ingredientId/edit': typeof AuthenticatedIngredientsIngredientIdEditRoute
  '/_authenticated/interactions/$ruleId/edit': typeof AuthenticatedInteractionsRuleIdEditRoute
  '/_authenticated/medications/$medicationId/edit': typeof AuthenticatedMedicationsMedicationIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/contraindications'
    | '/encounters'
    | '/ingredients'
    | '/interactions'
    | '/medications'
    | '/overview'
    | '/patients'
    | '/contraindications/new'
    | '/encounters/$encounterId'
    | '/ingredients/new'
    | '/interactions/new'
    | '/medications/$medicationId'
    | '/medications/link-ingredient'
    | '/medications/new'
    | '/patients/$patientId'
    | '/contraindications/$ruleId/edit'
    | '/ingredients/$ingredientId/edit'
    | '/interactions/$ruleId/edit'
    | '/medications/$medicationId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/contraindications'
    | '/encounters'
    | '/ingredients'
    | '/interactions'
    | '/medications'
    | '/overview'
    | '/patients'
    | '/contraindications/new'
    | '/encounters/$encounterId'
    | '/ingredients/new'
    | '/interactions/new'
    | '/medications/$medicationId'
    | '/medications/link-ingredient'
    | '/medications/new'
    | '/patients/$patientId'
    | '/contraindications/$ruleId/edit'
    | '/ingredients/$ingredientId/edit'
    | '/interactions/$ruleId/edit'
    | '/medications/$medicationId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/contraindications'
    | '/_authenticated/encounters'
    | '/_authenticated/ingredients'
    | '/_authenticated/interactions'
    | '/_authenticated/medications'
    | '/_authenticated/overview'
    | '/_authenticated/patients'
    | '/_authenticated/contraindications/new'
    | '/_authenticated/encounters/$encounterId'
    | '/_authenticated/ingredients/new'
    | '/_authenticated/interactions/new'
    | '/_authenticated/medications/$medicationId'
    | '/_authenticated/medications/link-ingredient'
    | '/_authenticated/medications/new'
    | '/_authenticated/patients/$patientId'
    | '/_authenticated/contraindications/$ruleId/edit'
    | '/_authenticated/ingredients/$ingredientId/edit'
    | '/_authenticated/interactions/$ruleId/edit'
    | '/_authenticated/medications/$medicationId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/medications': {
      id: '/_authenticated/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof AuthenticatedMedicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interactions': {
      id: '/_authenticated/interactions'
      path: '/interactions'
      fullPath: '/interactions'
      preLoaderRoute: typeof AuthenticatedInteractionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ingredients': {
      id: '/_authenticated/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof AuthenticatedIngredientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/encounters': {
      id: '/_authenticated/encounters'
      path: '/encounters'
      fullPath: '/encounters'
      preLoaderRoute: typeof AuthenticatedEncountersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contraindications': {
      id: '/_authenticated/contraindications'
      path: '/contraindications'
      fullPath: '/contraindications'
      preLoaderRoute: typeof AuthenticatedContraindicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/$patientId': {
      id: '/_authenticated/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedPatientsRoute
    }
    '/_authenticated/medications/new': {
      id: '/_authenticated/medications/new'
      path: '/new'
      fullPath: '/medications/new'
      preLoaderRoute: typeof AuthenticatedMedicationsNewRouteImport
      parentRoute: typeof AuthenticatedMedicationsRoute
    }
    '/_authenticated/medications/link-ingredient': {
      id: '/_authenticated/medications/link-ingredient'
      path: '/link-ingredient'
      fullPath: '/medications/link-ingredient'
      preLoaderRoute: typeof AuthenticatedMedicationsLinkIngredientRouteImport
      parentRoute: typeof AuthenticatedMedicationsRoute
    }
    '/_authenticated/medications/$medicationId': {
      id: '/_authenticated/medications/$medicationId'
      path: '/$medicationId'
      fullPath: '/medications/$medicationId'
      preLoaderRoute: typeof AuthenticatedMedicationsMedicationIdRouteImport
      parentRoute: typeof AuthenticatedMedicationsRoute
    }
    '/_authenticated/interactions/new': {
      id: '/_authenticated/interactions/new'
      path: '/new'
      fullPath: '/interactions/new'
      preLoaderRoute: typeof AuthenticatedInteractionsNewRouteImport
      parentRoute: typeof AuthenticatedInteractionsRoute
    }
    '/_authenticated/ingredients/new': {
      id: '/_authenticated/ingredients/new'
      path: '/new'
      fullPath: '/ingredients/new'
      preLoaderRoute: typeof AuthenticatedIngredientsNewRouteImport
      parentRoute: typeof AuthenticatedIngredientsRoute
    }
    '/_authenticated/encounters/$encounterId': {
      id: '/_authenticated/encounters/$encounterId'
      path: '/$encounterId'
      fullPath: '/encounters/$encounterId'
      preLoaderRoute: typeof AuthenticatedEncountersEncounterIdRouteImport
      parentRoute: typeof AuthenticatedEncountersRoute
    }
    '/_authenticated/contraindications/new': {
      id: '/_authenticated/contraindications/new'
      path: '/new'
      fullPath: '/contraindications/new'
      preLoaderRoute: typeof AuthenticatedContraindicationsNewRouteImport
      parentRoute: typeof AuthenticatedContraindicationsRoute
    }
    '/_authenticated/medications/$medicationId/edit': {
      id: '/_authenticated/medications/$medicationId/edit'
      path: '/edit'
      fullPath: '/medications/$medicationId/edit'
      preLoaderRoute: typeof AuthenticatedMedicationsMedicationIdEditRouteImport
      parentRoute: typeof AuthenticatedMedicationsMedicationIdRoute
    }
    '/_authenticated/interactions/$ruleId/edit': {
      id: '/_authenticated/interactions/$ruleId/edit'
      path: '/$ruleId/edit'
      fullPath: '/interactions/$ruleId/edit'
      preLoaderRoute: typeof AuthenticatedInteractionsRuleIdEditRouteImport
      parentRoute: typeof AuthenticatedInteractionsRoute
    }
    '/_authenticated/ingredients/$ingredientId/edit': {
      id: '/_authenticated/ingredients/$ingredientId/edit'
      path: '/$ingredientId/edit'
      fullPath: '/ingredients/$ingredientId/edit'
      preLoaderRoute: typeof AuthenticatedIngredientsIngredientIdEditRouteImport
      parentRoute: typeof AuthenticatedIngredientsRoute
    }
    '/_authenticated/contraindications/$ruleId/edit': {
      id: '/_authenticated/contraindications/$ruleId/edit'
      path: '/$ruleId/edit'
      fullPath: '/contraindications/$ruleId/edit'
      preLoaderRoute: typeof AuthenticatedContraindicationsRuleIdEditRouteImport
      parentRoute: typeof AuthenticatedContraindicationsRoute
    }
  }
}

interface AuthenticatedContraindicationsRouteChildren {
  AuthenticatedContraindicationsNewRoute: typeof AuthenticatedContraindicationsNewRoute
  AuthenticatedContraindicationsRuleIdEditRoute: typeof AuthenticatedContraindicationsRuleIdEditRoute
}

const AuthenticatedContraindicationsRouteChildren: AuthenticatedContraindicationsRouteChildren =
  {
    AuthenticatedContraindicationsNewRoute:
      AuthenticatedContraindicationsNewRoute,
    AuthenticatedContraindicationsRuleIdEditRoute:
      AuthenticatedContraindicationsRuleIdEditRoute,
  }

const AuthenticatedContraindicationsRouteWithChildren =
  AuthenticatedContraindicationsRoute._addFileChildren(
    AuthenticatedContraindicationsRouteChildren,
  )

interface AuthenticatedEncountersRouteChildren {
  AuthenticatedEncountersEncounterIdRoute: typeof AuthenticatedEncountersEncounterIdRoute
}

const AuthenticatedEncountersRouteChildren: AuthenticatedEncountersRouteChildren =
  {
    AuthenticatedEncountersEncounterIdRoute:
      AuthenticatedEncountersEncounterIdRoute,
  }

const AuthenticatedEncountersRouteWithChildren =
  AuthenticatedEncountersRoute._addFileChildren(
    AuthenticatedEncountersRouteChildren,
  )

interface AuthenticatedIngredientsRouteChildren {
  AuthenticatedIngredientsNewRoute: typeof AuthenticatedIngredientsNewRoute
  AuthenticatedIngredientsIngredientIdEditRoute: typeof AuthenticatedIngredientsIngredientIdEditRoute
}

const AuthenticatedIngredientsRouteChildren: AuthenticatedIngredientsRouteChildren =
  {
    AuthenticatedIngredientsNewRoute: AuthenticatedIngredientsNewRoute,
    AuthenticatedIngredientsIngredientIdEditRoute:
      AuthenticatedIngredientsIngredientIdEditRoute,
  }

const AuthenticatedIngredientsRouteWithChildren =
  AuthenticatedIngredientsRoute._addFileChildren(
    AuthenticatedIngredientsRouteChildren,
  )

interface AuthenticatedInteractionsRouteChildren {
  AuthenticatedInteractionsNewRoute: typeof AuthenticatedInteractionsNewRoute
  AuthenticatedInteractionsRuleIdEditRoute: typeof AuthenticatedInteractionsRuleIdEditRoute
}

const AuthenticatedInteractionsRouteChildren: AuthenticatedInteractionsRouteChildren =
  {
    AuthenticatedInteractionsNewRoute: AuthenticatedInteractionsNewRoute,
    AuthenticatedInteractionsRuleIdEditRoute:
      AuthenticatedInteractionsRuleIdEditRoute,
  }

const AuthenticatedInteractionsRouteWithChildren =
  AuthenticatedInteractionsRoute._addFileChildren(
    AuthenticatedInteractionsRouteChildren,
  )

interface AuthenticatedMedicationsMedicationIdRouteChildren {
  AuthenticatedMedicationsMedicationIdEditRoute: typeof AuthenticatedMedicationsMedicationIdEditRoute
}

const AuthenticatedMedicationsMedicationIdRouteChildren: AuthenticatedMedicationsMedicationIdRouteChildren =
  {
    AuthenticatedMedicationsMedicationIdEditRoute:
      AuthenticatedMedicationsMedicationIdEditRoute,
  }

const AuthenticatedMedicationsMedicationIdRouteWithChildren =
  AuthenticatedMedicationsMedicationIdRoute._addFileChildren(
    AuthenticatedMedicationsMedicationIdRouteChildren,
  )

interface AuthenticatedMedicationsRouteChildren {
  AuthenticatedMedicationsMedicationIdRoute: typeof AuthenticatedMedicationsMedicationIdRouteWithChildren
  AuthenticatedMedicationsLinkIngredientRoute: typeof AuthenticatedMedicationsLinkIngredientRoute
  AuthenticatedMedicationsNewRoute: typeof AuthenticatedMedicationsNewRoute
}

const AuthenticatedMedicationsRouteChildren: AuthenticatedMedicationsRouteChildren =
  {
    AuthenticatedMedicationsMedicationIdRoute:
      AuthenticatedMedicationsMedicationIdRouteWithChildren,
    AuthenticatedMedicationsLinkIngredientRoute:
      AuthenticatedMedicationsLinkIngredientRoute,
    AuthenticatedMedicationsNewRoute: AuthenticatedMedicationsNewRoute,
  }

const AuthenticatedMedicationsRouteWithChildren =
  AuthenticatedMedicationsRoute._addFileChildren(
    AuthenticatedMedicationsRouteChildren,
  )

interface AuthenticatedPatientsRouteChildren {
  AuthenticatedPatientsPatientIdRoute: typeof AuthenticatedPatientsPatientIdRoute
}

const AuthenticatedPatientsRouteChildren: AuthenticatedPatientsRouteChildren = {
  AuthenticatedPatientsPatientIdRoute: AuthenticatedPatientsPatientIdRoute,
}

const AuthenticatedPatientsRouteWithChildren =
  AuthenticatedPatientsRoute._addFileChildren(
    AuthenticatedPatientsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedContraindicationsRoute: typeof AuthenticatedContraindicationsRouteWithChildren
  AuthenticatedEncountersRoute: typeof AuthenticatedEncountersRouteWithChildren
  AuthenticatedIngredientsRoute: typeof AuthenticatedIngredientsRouteWithChildren
  AuthenticatedInteractionsRoute: typeof AuthenticatedInteractionsRouteWithChildren
  AuthenticatedMedicationsRoute: typeof AuthenticatedMedicationsRouteWithChildren
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedContraindicationsRoute:
    AuthenticatedContraindicationsRouteWithChildren,
  AuthenticatedEncountersRoute: AuthenticatedEncountersRouteWithChildren,
  AuthenticatedIngredientsRoute: AuthenticatedIngredientsRouteWithChildren,
  AuthenticatedInteractionsRoute: AuthenticatedInteractionsRouteWithChildren,
  AuthenticatedMedicationsRoute: AuthenticatedMedicationsRouteWithChildren,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
